name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Nextcloud ${{ matrix.nextcloud }} - ${{ matrix.db.name }}
    strategy:
      matrix:
        db:
          - name: mysql
            image: mariadb:11.4
            username: root
            database: nextcloud
            port: 3306
          - name: pgsql
            image: postgres:17.5
            username: postgres
            database: postgres
            port: 5432
        nextcloud: [31]
    services:
      db:
        image: ${{ matrix.db.image }}
        env:
          MARIADB_ROOT_PASSWORD: password
          POSTGRES_PASSWORD: password
    container:
      image: nextcloud:${{ matrix.nextcloud }}
    steps:
      - name: Copy Nextcloud source
        run: ln -s /usr/src/nextcloud/* ${GITHUB_WORKSPACE}/

      - uses: actions/checkout@v4
        with:
          path: apps/fulltextsearch_sql

      # We only need external dependencies for PDF processing, so we can skip the composer install step.

      - name: Wait for database to get ready
        run: while ! bash -c "echo -n > /dev/tcp/db/${{ matrix.db.port }}" 2> /dev/null; do sleep 1; done

      - name: Install nextcloud
        run: >
          php occ -n maintenance:install \
            --admin-pass=admin \
            --database=${{ matrix.db.name }} \
            --database-host=db \
            --database-user=${{ matrix.db.username }} \
            --database-pass=password \
            --database-name=${{ matrix.db.database }}

      - name: Enable fulltextsearch app
        run: php occ -n app:enable fulltextsearch
      
      - name: Enable fulltextsearch_sql app
        run: php occ -n app:enable fulltextsearch_sql
      
      - name: Configure fulltextsearch_sql as platform
        run: >
          php occ -n fulltextsearch:configure '{"search_platform": "OCA\\FullTextSearch_SQL\\Platform\\SQLPlatform"}'

      # This can be removed as soon as https://github.com/nextcloud/fulltextsearch/pull/915 is merged.
      - name: Fix test harness
        run: >
          sed -i \
            -e "s/'document is a simple test'/'document is a'/" \
            -e "s/document is a simple -test/document -test/" \
            custom_apps/fulltextsearch/lib/Command/Test.php

      - name: Run fulltextsearch test
        run: php occ -n fulltextsearch:test --platform_delay 1